/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoLogout: typeof import('./src/components/AutoLogout.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatWidget: typeof import('./src/components/ChatWidget.vue')['default']
    ChatWidgetOld: typeof import('./src/components/ChatWidgetOld.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    Collections: typeof import('./src/components/Collections.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GlossarySearchNav: typeof import('./src/components/GlossarySearchNav.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    JsonSchemaViewer: typeof import('./src/components/JsonSchemaViewer.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MessageDocsJsonSchemaSearchNav: typeof import('./src/components/MessageDocsJsonSchemaSearchNav.vue')['default']
    MessageDocsSearchNav: typeof import('./src/components/MessageDocsSearchNav.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchNav: typeof import('./src/components/SearchNav.vue')['default']
    SvelteDropdown: typeof import('./src/components/SvelteDropdown.vue')['default']
    ToolCall: typeof import('./src/components/ToolCall.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
