FROM node:lts-bullseye as builder
# Add application sources
ADD .. /home/node/app/
WORKDIR /home/node/app
# Install the dependencies
COPY Dockerfiles/frontend_build.env /home/node/app/.env
RUN npm install
RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-120
USER 0
RUN dnf update -y
RUN chown -R 1001 /var/log/nginx
ADD Dockerfiles/nginx.conf "${NGINX_DEFAULT_CONF_PATH}"
COPY --from=builder /home/node/app/dist /opt/app-root/src
RUN chgrp -R 0 /opt/app-root/src/ && chmod -R g+rwX /opt/app-root/src/
USER 1001
CMD sed -i "s@replaceobpapihost@$VITE_OBP_API_HOST@g" /home/app/dist/index*.js ; nginx -g "daemon off;"




