FROM node:lts-slim as builder
# Add application sources
ADD .. /home/node/app/
WORKDIR /home/node/app
# Install the dependencies
COPY Dockerfiles/frontend_build.env /home/node/app/.env
RUN npm install
RUN npm run build

FROM golang:bookworm as gobuilder

WORKDIR /usr/src/app
COPY Dockerfiles/prestart.go ./main.go
COPY Dockerfiles/go.mod ./

RUN go  build -v -o /usr/src/app/prestart

FROM registry.access.redhat.com/ubi9/nginx-120
USER 0
RUN dnf update -y
RUN chown -R 1001 /var/log/nginx
ADD Dockerfiles/nginx.conf "${NGINX_DEFAULT_CONF_PATH}"
COPY --from=builder /home/node/app/dist /opt/app-root/src
COPY --from=gobuilder /usr/src/app/prestart /bin/prestart

RUN chgrp -R 0 /opt/app-root/src/ && chmod -R g+rwX /opt/app-root/src/
USER 1001
CMD /bin/prestart ; nginx -g "daemon off;"




