/*
 * Open Bank Project -  API Explorer II
 * Copyright (C) 2023-2024, TESOBE GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Email: contact@tesobe.com
 * TESOBE GmbH
 * Osloerstrasse 16/17
 * Berlin 13359, Germany
 *
 *   This product includes software developed at
 *   TESOBE (http://www.tesobe.com/)
 *
 */

import crypto from 'crypto'

/**
 * PKCE (Proof Key for Code Exchange) utilities for OAuth2 authorization code flow
 *
 * PKCE is a security extension to OAuth 2.0 for public clients on mobile and browser-based apps.
 * It mitigates authorization code interception attacks by using a dynamically created
 * cryptographic random key called "code verifier" and its transformed value called
 * "code challenge".
 *
 * @see RFC 7636: https://datatracker.ietf.org/doc/html/rfc7636
 */
export class PKCEUtils {
  /**
   * Generates a cryptographically random code verifier
   *
   * The code verifier is a high-entropy cryptographic random string using the
   * unreserved characters [A-Z] / [a-z] / [0-9] / "-" / "." / "_" / "~"
   * with a minimum length of 43 characters and a maximum length of 128 characters.
   *
   * @returns {string} Base64url-encoded random string (43 characters)
   *
   * @example
   * const verifier = PKCEUtils.generateCodeVerifier()
   * // Returns: "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk"
   */
  static generateCodeVerifier(): string {
    // Generate 32 random bytes and encode as base64url (results in 43 characters)
    return crypto.randomBytes(32).toString('base64url')
  }

  /**
   * Generates a code challenge from a code verifier using SHA256
   *
   * The code challenge is the Base64url encoding of the SHA256 hash of the code verifier.
   * This is sent to the authorization server during the initial authorization request.
   *
   * @param {string} verifier - The code verifier to transform
   * @returns {string} Base64url-encoded SHA256 hash of the verifier
   *
   * @example
   * const verifier = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk"
   * const challenge = PKCEUtils.generateCodeChallenge(verifier)
   * // Returns: "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"
   */
  static generateCodeChallenge(verifier: string): string {
    // Create SHA256 hash of the verifier and encode as base64url
    return crypto.createHash('sha256').update(verifier).digest('base64url')
  }

  /**
   * Generates a cryptographically random state parameter
   *
   * The state parameter is used to maintain state between the authorization request
   * and the callback. It also serves as a CSRF token to prevent cross-site request forgery attacks.
   *
   * @returns {string} Hex-encoded random string (64 characters)
   *
   * @example
   * const state = PKCEUtils.generateState()
   * // Returns: "af0ifjsldkj"
   */
  static generateState(): string {
    // Generate 32 random bytes and encode as hex (results in 64 characters)
    return crypto.randomBytes(32).toString('hex')
  }

  /**
   * Validates a code verifier format
   *
   * According to RFC 7636, a code verifier must be:
   * - Between 43 and 128 characters long
   * - Use only unreserved characters: [A-Z] / [a-z] / [0-9] / "-" / "." / "_" / "~"
   *
   * @param {string} verifier - The code verifier to validate
   * @returns {boolean} True if the verifier is valid, false otherwise
   */
  static isValidCodeVerifier(verifier: string): boolean {
    if (!verifier || typeof verifier !== 'string') {
      return false
    }

    // Check length (43-128 characters)
    if (verifier.length < 43 || verifier.length > 128) {
      return false
    }

    // Check allowed characters (unreserved characters only)
    const validPattern = /^[A-Za-z0-9\-._~]+$/
    return validPattern.test(verifier)
  }

  /**
   * Validates a state parameter format
   *
   * @param {string} state - The state parameter to validate
   * @returns {boolean} True if the state is valid, false otherwise
   */
  static isValidState(state: string): boolean {
    if (!state || typeof state !== 'string') {
      return false
    }

    // State should be at least 32 characters for security
    if (state.length < 32) {
      return false
    }

    // Check it's a valid hex string (if generated by generateState)
    const hexPattern = /^[a-f0-9]+$/
    return hexPattern.test(state)
  }
}
